# Generated by Django 3.1.4 on 2020-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('transno', models.PositiveIntegerField()),
                ('maxp', models.PositiveIntegerField()),
                ('minp', models.PositiveIntegerField()),
                ('closep', models.PositiveIntegerField()),
                ('tradedshares', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('prevclosep', models.PositiveIntegerField()),
                ('diff', models.IntegerField()),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('sn', models.IntegerField()),
            ],
        ),
    ]
