# Generated by Django 3.1.4 on 2020-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_stock_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sector', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'company_list',
            },
        ),
    ]
