# Generated by Django 3.1.4 on 2020-12-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_floorsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorsheet',
            name='contractnum',
            field=models.BigIntegerField(),
        ),
    ]
